
name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.0
    - name: install rush
      run: npm install -g @microsoft/rush
    - name: rush change
      run: rush change -v
    - name: rush install
      run: rush install --no-link
    - name: rush link
      run: rush link
    - name: rush build
      run: rush build --verbose
    - name: rush deploy
      run: rush deploy --overwrite -p @junow/rush-core
    - name: Add GiHub Package Token
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc
    - name: deploy @junow/rush-core
      run: cd common/deploy/packages/core && npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
